# Generated by Django 5.1.4 on 2024-12-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('user_rating', models.FloatField(default=0.0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movies/covers/')),
            ],
        ),
    ]
